# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "antir-engine"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fernando Alonso"]
  s.date = "2011-12-23"
  s.description = "AntirEngine VPSs configuration interface"
  s.email = "krakatoa1987@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "antir-engine.gemspec",
    "lib/antir-engine.rb",
    "lib/antir/engine.rb",
    "lib/antir/hypervisor.rb",
    "lib/antir/hypervisor/domain_handler.rb",
    "lib/antir/vps.rb",
    "lib/antir/vps/xml.rb",
    "spec/engine_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/krakatoa/antir-engine"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "AntirEngine configuration tool"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cucub-object>, [">= 0"])
      s.add_runtime_dependency(%q<bson>, [">= 1.3.1"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 1.3.1"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 1.1.4"])
      s.add_runtime_dependency(%q<libvirt>, [">= 0.2.0"])
      s.add_runtime_dependency(%q<redis>, [">= 2.2.2"])
      s.add_runtime_dependency(%q<json>, [">= 1.6.1"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.6.7"])
      s.add_runtime_dependency(%q<sigar>, ["= 0.7.0"])
      s.add_runtime_dependency(%q<antir-machine>, ["= 0.1.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<cucub-object>, [">= 0"])
      s.add_dependency(%q<bson>, [">= 1.3.1"])
      s.add_dependency(%q<bson_ext>, [">= 1.3.1"])
      s.add_dependency(%q<libxml-ruby>, [">= 1.1.4"])
      s.add_dependency(%q<libvirt>, [">= 0.2.0"])
      s.add_dependency(%q<redis>, [">= 2.2.2"])
      s.add_dependency(%q<json>, [">= 1.6.1"])
      s.add_dependency(%q<rest-client>, [">= 1.6.7"])
      s.add_dependency(%q<sigar>, ["= 0.7.0"])
      s.add_dependency(%q<antir-machine>, ["= 0.1.1"])
      s.add_dependency(%q<rspec>, ["~> 2.6"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<cucub-object>, [">= 0"])
    s.add_dependency(%q<bson>, [">= 1.3.1"])
    s.add_dependency(%q<bson_ext>, [">= 1.3.1"])
    s.add_dependency(%q<libxml-ruby>, [">= 1.1.4"])
    s.add_dependency(%q<libvirt>, [">= 0.2.0"])
    s.add_dependency(%q<redis>, [">= 2.2.2"])
    s.add_dependency(%q<json>, [">= 1.6.1"])
    s.add_dependency(%q<rest-client>, [">= 1.6.7"])
    s.add_dependency(%q<sigar>, ["= 0.7.0"])
    s.add_dependency(%q<antir-machine>, ["= 0.1.1"])
    s.add_dependency(%q<rspec>, ["~> 2.6"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

